version: "3"
services:
    takenote:
        container_name: takenote
        image: registry.gitlab.com/ht-moh/takenote
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - CLIENT_ID=${CLIENT_ID}
            - CLIENT_SECRET=${CLIENT_SECRET}